name: C++ CI with Conan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Conan
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install conan

      - name: Create Conan profile
        run: conan profile detect

      - name: Install dependencies with Conan
        run: conan install . --build=missing

      - name: Build the project
        run: |
          cmake --preset conan-release
          cmake --build --preset conan-release

      - name: Run tests
        run: |
          cd build
          ctest
